services:
  - type: web
    name: ai-api-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: FIREBASE_PRIVATE_KEY_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_CLIENT_ID
        sync: false
